### ISSUE TITLE
Connection to server is erroring & can't be stopped

### ISSUE THREAD

**Issue by snutij** [Shopify/vscode-ruby-lsp#573]
Hello, I'm having an issue since this weekend with the vscode extension. 

I have already tried: 
- uninstall totally & re-install vscode
- setting `auto`/`rbenv` on ruby version manager setting
- tried `BUNDLE_GEMFILE=/path_projet/.ruby-lsp/Gemfile bundle install`
- tried to open other ruby projects like `ruby-lsp` & `tapioca`
- If I reload the window, same issue.
- If I stop and start the Ruby LSP server, the same issue.
- If I restart the Ruby LSP server, the same issue, with no output logs, it's blocked in starting state but not working (no formatting or onTypeFormatting (like auto `end`).

```
Starting Ruby LSP...
[Error - 11:50:34 PM] Client Ruby LSP: connection to server is erroring. Shutting down server.
[Error - 11:50:34 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
    at yd.shutdown (/Users/justinrabiller/.vscode/extensions/shopify.ruby-lsp-0.2.4/out/extension.js:39:8615)
    at yd.stop (/Users/justinrabiller/.vscode/extensions/shopify.ruby-lsp-0.2.4/out/extension.js:39:8194)
    at yd.stop (/Users/justinrabiller/.vscode/extensions/shopify.ruby-lsp-0.2.4/out/extension.js:39:51160)
    at yd.handleConnectionError (/Users/justinrabiller/.vscode/extensions/shopify.ruby-lsp-0.2.4/out/extension.js:39:13955)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
``` 

Here all notifications: 

<img width="467" alt="image" src="https://user-images.githubusercontent.com/38727166/234127290-9486b90a-e52b-47c2-879d-e510510c1740.png">

Here, we can see that Ruby LSP is still in starting state:

<img width="127" alt="image" src="https://user-images.githubusercontent.com/38727166/234127414-2c18f27a-b51f-4937-b8a6-c6ee7945e600.png">

With the `Run extension` debug task, I saw it failed at: 

https://github.com/Shopify/vscode-ruby-lsp/blob/18e48e821ad8568682392bf1a12c429f787fab61/src/client.ts#L191

To be honest, it was working like a charm the past week, so I probably did something wrong but I can't know what 🤔   

Do not hesitate if you need more input.

**Comment by andyw8** [comment]
Hi @snutij,

Could you try an older version of the extension to see if it behaves the same way? (Use "Install Another Version" from the settings icon next the extension).

**Comment by snutij** [comment]
Hello 👋 

First good news: it's working now! I left half my soul in this debug but I learned a lot!

Updating to v0.2.5, with all extensions disabled except `ruby-lsp` didn't fix the issue. 

So I went further in the debugging, quite far in `languageserver-node`, until this line of the `jsonrpc` package: https://github.com/microsoft/vscode-languageserver-node/blob/1320922f95ef182df2cf76b7c96b1a2d3ba14c2a/jsonrpc/src/common/messageReader.ts#L221-L224

Where the header variable looked really weird to me:

<img width="975" alt="Screenshot 2023-04-25 at 23 47 08" src="https://user-images.githubusercontent.com/38727166/234533048-fbb78564-f40a-4e93-9ecb-e490f21d5ea1.png">

So the real error raised on my issue was: `Header must provide a Content-Length property`

This repetition of `toto` is kind of our "French foobar", clearly a line I wrote in my own ruby-lsp fork to debug something.

Why my own fork was used to run the `ruby-lsp` server I have no idea. But even after deleting the fork, I still had this header.  So I came to suspect a cache issue somewhere.
 
- So I removed all my installed ruby versions: `rm -rf /Users/justinrabiller/.rbenv/versions/*`
- Then reinstall the version of my pro project with `rbenv install 3.2.2`
- Restarted vscode, and after a long (very long) `bundle install` the ruby-lsp server initialized without any problem!

I'm really sorry for the noise, it's clearly something wrong with my own setup, not an issue with the extensions itself. I close this issue so! 

Again thank you for your help. 🙏

**Comment by andyw8** [comment]
@snutij `bundle pristine ruby-lsp` may also have worked, it's handy for undo-ing changes after troubleshooting.
