### ISSUE TITLE
"Failed to activate none environment" with VS Code remote editing

### ISSUE THREAD

**Issue by perlun** [Shopify/vscode-ruby-lsp#835]
### Ruby version

ruby 3.0.6p216

### Description

Hi,

When trying to use `ruby-lsp` via VS Code SSH-remote-editing towards a machine _without Ruby installed_ system-wide, I get the error below:

```
Failed to activate none environment: Command failed: /bin/bash -ic 'ruby -rjson -e "printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump(ENV.to_h))"' bash: cannot set terminal process group (4182976): Inappropriate ioctl for device bash: no job control in this shell Command 'ruby' not found, but can be installed with: sudo snap install ruby # version 3.2.2, or sudo apt install ruby # version 1:3.0~exp1 See 'snap info ruby' for additional versions.
```

However, the Ruby I want to use is available in `/opt/gitlab/embedded/bin`. I have this directory added to the `PATH` via `.profile_secrets`, which in turn gets loaded via `.profile`, but I presume this isn't loaded when opening the directory using VS Code SSH-remote editing.

Any ideas on how to resolve this? I'd prefer to _not_ have to install Ruby system-wide on this machine, since it's a production server.

### Expected output

No error on startup

**Comment by perlun** [comment]
Thanks @vinistock! :+1: That worked much better, but now I am running into this:

```
Failed to setup the bundle: Command failed: gem install ruby-lsp
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /opt/gitlab/embedded/lib/ruby/gems/3.0.0 directory.
	/opt/gitlab/embedded/lib/ruby/site_ruby/3.0.0/rubygems/installer.rb:715:in `verify_gem_home'
	/opt/gitlab/embedded/lib/ruby/site_ruby/3.0.0/rubygems/installer.rb:905:in `pre_install_checks'
	/opt/gitlab/embedded/lib/ruby/site_ruby/3.0.0/rubygems/installer.rb:303:in `install'
	/opt/gitlab/embedded/lib/ruby/site_ruby/3.0.0/rubygems/resolver/specification.rb:105:in `install'
	/opt/gitlab/embedded/lib/ruby/site_ruby/3.0.0/rubygems/request_set.rb:195:in `block in install'
	/opt/gitlab/embedded/lib/ruby/site_ruby/3.0.0/rubygems/request_set.rb:183:in `each'
	/opt/gitlab/embedded/lib/ruby/site_ruby/3.0.0/rubygems/request_set.rb:183:in `install'
	/opt/gitlab/embedded/lib/ruby/site_ruby/3.0.0/rubygems/commands/install_command.rb:215:in `install_gem'
	/opt/gitlab/embedded/lib/ruby/site_ruby/3.0.0/rubygems/commands/install_command.rb:231:in `block in install_gems'
	/opt/gitlab/embedded/lib/ruby/site_ruby/3.0.0/rubygems/commands/install_command.rb:224:in `each'
	/opt/gitlab/embedded/lib/ruby/site_ruby/3.0.0/rubygems/commands/install_command.rb:224:in `install_gems'
	/opt/gitlab/embedded/lib/ruby/site_ruby/3.0.0/rubygems/commands/install_command.rb:170:in `execute'
	/opt/gitlab/embedded/lib/ruby/site_ruby/3.0.0/rubygems/command.rb:328:in `invoke_with_build_args'
	/opt/gitlab/embedded/lib/ruby/site_ruby/3.0.0/rubygems/command_manager.rb:253:in `invoke_command'
	/opt/gitlab/embedded/lib/ruby/site_ruby/3.0.0/rubygems/command_manager.rb:193:in `process_args'
	/opt/gitlab/embedded/lib/ruby/site_ruby/3.0.0/rubygems/command_manager.rb:151:in `run'
	/opt/gitlab/embedded/lib/ruby/site_ruby/3.0.0/rubygems/gem_runner.rb:52:in `run'
	/opt/gitlab/embedded/bin/gem:12:in `<main>'
.             See [Troubleshooting](https://github.com/Shopify/vscode-ruby-lsp#troubleshooting) for instructions
```

I guess this kind of environment ("use existing Ruby which you don't have write-access to") is kind of an edge case? :thinking: Any suggested workarounds, apart from setting up a "new" empty userspace Ruby and then install the full set of gems present in the GitLab installation?

**Comment by perlun** [comment]
Makes sense, thanks. :+1: I'll live without the extension for now, it's only an environment I work in seldomly anyway.
