### ISSUE TITLE
Existing projects do not create the .ruby-lsp folder

### ISSUE THREAD

**Issue by davideluque** [Shopify/vscode-ruby-lsp#844]
### Operating System

MacOS Sonoma

### Ruby version

3.1.4

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

asdf

### Description

The extension is installed in VSCode, but when I open other projects, the server fails to start because the .ruby-lsp folder isn't created automatically, and there isn't a command to do so.

**Comment by soundnotation** [comment]
I believe I have the same bug using a different setup.
Windows 11 10.0.22621, WSL2 1.2.5.0, Ruby 3.2.2, RVM 1.29.10, Bundler 2.4.21, Ruby LSP gem 0.12.1, Ruby LSP VS Code extension 0.4.13.
Following is shown in the notification area in VS Code a few seconds after starting it:
```
Failed to setup the bundle: Command failed: gem install ruby-lsp
ERROR: While executing gem ... (Errno::EACCES) Permission denied @ dir_s_mkdir - /home/ubuntu/.rvm/gems/ruby-3.2.2
/home/simone/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/fileutils.rb:406:in `mkdir'
/home/simone/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/fileutils.rb:406:in `fu_mkdir'
/home/simone/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/fileutils.rb:384:in `block (2 levels) in mkdir_p'
/home/simone/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/fileutils.rb:382:in `reverse_each'
/home/simone/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/fileutils.rb:382:in `block in mkdir_p'
/home/simone/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/fileutils.rb:374:in `each'
/home/simone/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/fileutils.rb:374:in `mkdir_p'
/home/simone/.rvm/rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/installer.rb:712:in `verify_gem_home'
/home/simone/.rvm/rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/installer.rb:903:in `pre_instal...
```
Running the command `gem install ruby-lsp` in my project directory doesn't give any errors, but I have the gem already in my Gemfile anyway: `gem 'ruby-lsp', '>= 0.11.2'`. I also have the debug gem.
I have only this project open in VS Code, although I have other RoR projects in my home. No trace of the .ruby-lsp folder.

**Comment by andyw8** [comment]
@scheals just a little advice based what you said above:

It's almost always worth adding a `Gemfile.lock` to each project you work on. Otherwise you have no guarantee that it will work on another machine, since the gem versions may differ. It may even stop working on your own machhine, if you happen to install a newer version of a gem.

You can learn more here: https://bundler.io/guides/getting_started.html

**Comment by vinistock** [comment]
It's unclear to me if what @scheals has reported is exactly the same scenario as the original author's.

However, it is an issue indeed. We're currently not allowing the Ruby LSP to be used without any folders opened in VS Code (by early returning [here](https://github.com/Shopify/vscode-ruby-lsp/blob/0aa9e977d711a736f117446f40032bac2b4e57f8/src/extension.ts#L8)).

The fix is not super trivial though. We will need to add some CLI flag to the server to allow it being launched bypassing the custom bundle logic and then pass that flag when there are no folders opened in VS Code.
