### ISSUE TITLE
Not starting with RVM: .rvm/gems/ruby-3.2.2/bin/ruby: not found

### ISSUE THREAD

**Issue by soundnotation** [Shopify/vscode-ruby-lsp#880]
### Operating System

WSL on Windows 11

### Ruby version

3.2.2

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

rvm

### Description

I'm having troubles using the extension with VS Code and RVM.

As recommended by the docs, I don't have the ruby-lsp gem installed. I'm using v0.4.13 of the extension.

It crashes after starting VS Code. Below is the complete output.

The line that stuns me is the second to last one:
```
/home/simone/.rvm/gems/ruby-3.2.2/bin/ruby-lsp: 6: exec: /home/simone/.rvm/gems/ruby-3.2.2/bin/ruby: not found
```
It says that ruby is not found, whereas it is properly installed and working.
That `ruby` executable is somehow being searched under the `gems` directory, but `which ruby` gives `/home/simone/.rvm/rubies/ruby-3.2.2/bin/ruby`. So it's to be found under rubies, not gems (it's not a gem indeed!).

FYI, I start and use VS Code as user setup (i.e. "%userprofile%\AppData\Local\Programs\Microsoft VS Code\Code.exe"), either by Windows key + 'code' (search) or in a batch script for my environment boot, like this: `explorer.exe "%userprofile%\AppData\Local\Programs\Microsoft VS Code\Code.exe"`. Running the system setup (`"C:\Program Files\Microsoft VS Code\Code.exe"`) or `code .` from my project does not open any VS Code.

That's what I have in my WSL's `~/.bashrc`:
```
export GEM_HOME="$HOME/.rvm/gems/ruby-3.2.2"
export GEM_PATH="$HOME/.rvm/gems/ruby-3.2.2"
export PATH="$GEM_HOME/bin:$HOME/.rvm/bin:$PATH"
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
```
Complete VS Code output from Ruby LSP:
```
Ruby LSP> Checking if asdf is available on the path with command: /bin/bash -ic 'asdf --version'
Ruby LSP> Checking if chruby is available on the path with command: /bin/bash -ic 'chruby --version'
Ruby LSP> Checking if rbenv is available on the path with command: /bin/bash -ic 'rbenv --version'
Ruby LSP> Checking if rvm is available on the path with command: /bin/bash -ic 'rvm --version'
Ruby LSP> Discovered version manager rvm
Ruby LSP> Trying to activate Ruby environment with command: /bin/bash -ic 'rvm-auto-ruby -rjson -e "printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump(ENV.to_h))"' inside directory: /home/simone/my-project
[Error - 11:16:07 AM] Client Ruby LSP: connection to server is erroring.
write EPIPE
Shutting down server.
[Error - 11:16:07 AM] Client Ruby LSP: connection to server is erroring.
write EPIPE
[Error - 11:16:07 AM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at Hd.shutdown (/home/simone/.vscode-server/extensions/shopify.ruby-lsp-0.4.13/out/extension.js:41:8468)
	at Hd.stop (/home/simone/.vscode-server/extensions/shopify.ruby-lsp-0.4.13/out/extension.js:41:8047)
	at Hd.stop (/home/simone/.vscode-server/extensions/shopify.ruby-lsp-0.4.13/out/extension.js:44:38188)
	at Hd.handleConnectionError (/home/simone/.vscode-server/extensions/shopify.ruby-lsp-0.4.13/out/extension.js:43:63)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 11:16:07 AM] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 11:16:07 AM] Ruby LSP client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
Error restarting the server: write EPIPE
[Info  - 11:16:07 AM] Connection to server got closed. Server will restart.
true
/home/simone/.rvm/gems/ruby-3.2.2/bin/ruby-lsp: 6: exec: /home/simone/.rvm/gems/ruby-3.2.2/bin/ruby: not found
[Error - 11:16:07 AM] Server process exited with code 127.
[Error - 11:16:07 AM] Server process exited with code 127.
[Error - 11:16:07 AM] Client Ruby LSP: connection to server is erroring.
Cannot call write after a stream was destroyed
[Error - 11:16:07 AM] Server initialization failed.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 11:16:07 AM] Ruby LSP client: couldn't create connection to server.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 11:16:07 AM] Restarting server failed
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Info  - 11:16:07 AM] Connection to server got closed. Server will restart.
true
/home/simone/.rvm/gems/ruby-3.2.2/bin/ruby-lsp: 6: exec: /home/simone/.rvm/gems/ruby-3.2.2/bin/ruby: not found
[Error - 11:16:07 AM] Client Ruby LSP: connection to server is erroring.
write EPIPE
Shutting down server.
[Error - 11:16:07 AM] Client Ruby LSP: connection to server is erroring.
write EPIPE
[Error - 11:16:07 AM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at Hd.shutdown (/home/simone/.vscode-server/extensions/shopify.ruby-lsp-0.4.13/out/extension.js:41:8468)
	at Hd.stop (/home/simone/.vscode-server/extensions/shopify.ruby-lsp-0.4.13/out/extension.js:41:8047)
	at Hd.stop (/home/simone/.vscode-server/extensions/shopify.ruby-lsp-0.4.13/out/extension.js:44:38188)
	at Hd.handleConnectionError (/home/simone/.vscode-server/extensions/shopify.ruby-lsp-0.4.13/out/extension.js:43:63)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 11:16:07 AM] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 11:16:07 AM] Ruby LSP client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Error - 11:16:07 AM] Restarting server failed
  Message: write EPIPE
  Code: -32099 
[Info  - 11:16:07 AM] Connection to server got closed. Server will restart.
true
/home/simone/.rvm/gems/ruby-3.2.2/bin/ruby-lsp: 6: exec: /home/simone/.rvm/gems/ruby-3.2.2/bin/ruby: not found
[Error - 11:16:07 AM] Server process exited with code 127.
[Error - 11:16:07 AM] Server process exited with code 127.
[Error - 11:16:07 AM] Client Ruby LSP: connection to server is erroring.
Cannot call write after a stream was destroyed
[Error - 11:16:07 AM] Server initialization failed.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 11:16:07 AM] Ruby LSP client: couldn't create connection to server.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 11:16:07 AM] Restarting server failed
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Info  - 11:16:07 AM] Connection to server got closed. Server will restart.
true
/home/simone/.rvm/gems/ruby-3.2.2/bin/ruby-lsp: 6: exec: /home/simone/.rvm/gems/ruby-3.2.2/bin/ruby: not found
[Error - 11:16:07 AM] Client Ruby LSP: connection to server is erroring.
write EPIPE
Shutting down server.
[Error - 11:16:07 AM] Client Ruby LSP: connection to server is erroring.
write EPIPE
[Error - 11:16:07 AM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at Hd.shutdown (/home/simone/.vscode-server/extensions/shopify.ruby-lsp-0.4.13/out/extension.js:41:8468)
	at Hd.stop (/home/simone/.vscode-server/extensions/shopify.ruby-lsp-0.4.13/out/extension.js:41:8047)
	at Hd.stop (/home/simone/.vscode-server/extensions/shopify.ruby-lsp-0.4.13/out/extension.js:44:38188)
	at Hd.handleConnectionError (/home/simone/.vscode-server/extensions/shopify.ruby-lsp-0.4.13/out/extension.js:43:63)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 11:16:07 AM] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 11:16:07 AM] Ruby LSP client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Error - 11:16:07 AM] Restarting server failed
  Message: write EPIPE
  Code: -32099 
[Error - 11:16:07 AM] The Ruby LSP server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
/home/simone/.rvm/gems/ruby-3.2.2/bin/ruby-lsp: 6: exec: /home/simone/.rvm/gems/ruby-3.2.2/bin/ruby: not found
[Error - 11:16:07 AM] Server process exited with code 127.
```
WSL and Windows setup:

WSL-Version: 1.2.5.0
Kernelversion: 5.15.90.1
WSLg-Version: 1.0.51
MSRDC-Version: 1.2.3770
Direct3D-Version: 1.608.2-61064218
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows-Version: 10.0.22621.2506

VS Code setup:

Version: 1.84.1 (user setup)
Commit: 2b35e1e6d88f1ce073683991d1eff5284a32690f
Date: 2023-11-06T12:35:59.022Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by vinistock** [comment]
Thank you for the bug report!

If you try to run our Ruby activation script in your terminal. Does it work properly?

```shell
# This uses bash to run a single command in interactive mode (which loads the ~/.bashrc file)
# The command uses `rvm-auto-ruby` to select the correct Ruby version based on your RVM config
# And then just prints the environment variables relevant to Ruby

/bin/bash -ic 'rvm-auto-ruby -rjson -e "printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump(ENV.to_h))"'
```

I suspect that `rvm-auto-ruby` is pointing to the wrong Ruby for some reason.

**Comment by vinistock** [comment]
No, not all of them. Did it print a JSON containing your environment variables? And does any of them include the path where the extension says it cannot find Ruby?

```shell
# Is this path present anywhere?
/home/simone/.rvm/gems/ruby-3.2.2
```

If that path is in `RUBY_ROOT`, for example, then for some reason using `rvm-auto-ruby` is pointing to the wrong Ruby path. Then, we'll need to understand if

- This is an issue with configuration
- If `rvm-auto-ruby` maybe does not work as we expected

**Comment by soundnotation** [comment]
It prints the JSON and the `/home/simone/.rvm/gems/ruby-3.2.2` path is only found within GEM_HOME, GEM_PATH and PATH (as prerequisites for RVM).
Following is a partial result of the command (with the vars I think are useful for the case):
```
RUBY_ENV_ACTIVATE{"SHELL":"/bin/bash","NVM_INC":"/home/simone/.nvm/versions/node/v14.15.0/include/node","WSL2_GUI_APPS_ENABLED":"1","rvm_delete_flag":"0","rvm_prefix":"/home/simone","WSL_DISTRO_NAME":"Ubuntu","MY_RUBY_HOME":"/home/simone/.rvm/rubies/ruby-3.2.2","RUBY_VERSION":"ruby-3.2.2","rvm_version":"1.29.12 (latest)","rvm_create_flag":"1","HOME":"/home/simone","LANG":"C.UTF-8","WSL_INTEROP":"/run/WSL/542_interop","LS_COLORS":"rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:","WAYLAND_DISPLAY":"wayland-0","NVM_DIR":"/home/simone/.nvm","rvm_bin_path":"/home/simone/.rvm/bin","GEM_PATH":"/home/simone/.rvm/gems/ruby-3.2.2:/home/simone/.rvm/gems/ruby-3.2.2@global","GEM_HOME":"/home/simone/.rvm/gems/ruby-3.2.2","LESSCLOSE":"/usr/bin/lesspipe %s %s","TERM":"xterm-256color","LESSOPEN":"| /usr/bin/lesspipe %s","USER":"simone","DISPLAY":":0","SHLVL":"2","NVM_CD_FLAGS":"","rvm_ruby_string":"ruby-3.2.2","XDG_RUNTIME_DIR":"/run/user/1000/","WSLENV":"WT_SESSION:WT_PROFILE_ID:USERPROFILE/up","PATH":"/home/simone/.rvm/gems/ruby-3.2.2/bin:/home/simone/.rvm/gems/ruby-3.2.2@global/bin:/home/simone/.rvm/rubies/ruby-3.2.2/bin:/home/simone/.rvm/bin:/home/simone/.yarn/bin:/home/simone/.config/yarn/global/node_modules/.bin:/home/simone/.local/bin:/home/simone/bin:/home/simone/.nvm/versions/node/v14.15.0/bin:/home/simone/.yarn/bin:/home/simone/.config/yarn/global/node_modules/.bin:/home/simone/.local/bin:/home/simone/bin:/home/simone/.local/bin:/home/simone/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files/Common Files/Oracle/Java/javapath:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0:/mnt/c/WINDOWS/System32/OpenSSH:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/PuTTY:/mnt/c/Program Files (x86)/Common Files/Propellerhead Software/ReWire:/mnt/c/Program Files/Common Files/Propellerhead Software/ReWire:/mnt/c/Program Files (x86)/Calibre2:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/MinGW/bin:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Program Files/dotnet:/mnt/c/Users/SimoneErlisoundnotat/AppData/Local/Programs/Python/Python38/Scripts:/mnt/c/Users/SimoneErlisoundnotat/AppData/Local/Programs/Python/Python38:/mnt/c/Users/SimoneErlisoundnotat/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/SimoneErlisoundnotat/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/SimoneErlisoundnotat/AppData/Roaming/Amazon:/mnt/c/Users/SimoneErlisoundnotat/AppData/Local/Microsoft/WindowsApps:/usr/bin/python3.6:/usr/bin/python3.6","DBUS_SESSION_BUS_ADDRESS":"unix:path=/run/user/1000/bus","NVM_BIN":"/home/simone/.nvm/versions/node/v14.15.0/bin","HOSTTYPE":"x86_64","IRBRC":"/home/simone/.rvm/rubies/ruby-3.2.2/.irbrc","PULSE_SERVER":"unix:/mnt/wslg/PulseServer","rvm_path":"/home/simone/.rvm}RUBY_ENV_ACTIVATE
```

**Comment by vinistock** [comment]
Okay, we seem to be narrowing down the issue.

> (FYI, bundle exec ruby-lsp gives the same error as well)

With bundle exec, we should never reach that same line. Is the backtrace really the same?

Can you try this?

- Clone the server https://github.com/Shopify/ruby-lsp
- Above [this line](https://github.com/Shopify/ruby-lsp/blob/341bf2273ebdd83f87282c533445e4015146d78b/exe/ruby-lsp#L68) add
```ruby
warn(ENV["PATH"])
```
- Below [this line](https://github.com/Shopify/ruby-lsp/blob/341bf2273ebdd83f87282c533445e4015146d78b/exe/ruby-lsp#L71) add
```ruby
warn(ENV["PATH"])
```
- Report back about whether `/home/simone/.rvm/rubies/ruby-3.2.2/bin` is present in any of the two prints

For some reason, it seems like the directory where RVM install Ruby is not in the path when we try to boot the LSP. Not sure why just yet.
