### ISSUE TITLE
ruby-lsp Crashes: can't find executable ruby-lsp for gem ruby-lsp

### ISSUE THREAD

**Issue by truecar-mvelez** [Shopify/vscode-ruby-lsp#881]
### Operating System

macOS 13.6

### Ruby version

3.2.2

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

other (please specify in description)

### Description

I installed this extension as the main Ruby one is now depreciated, and I use `rtx` to manage my Ruby versions.

I keep getting the below error every time VSCode starts up.

I've followed the troubleshooting guide (and ensured the `rtx` eval command is in my settings. I already had the `ruby-lsp` gem installed, and even after uninstalling it and deleting the `.ruby-lsp/` directory, the issue persists.

I can verify that `/Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/ruby-lsp` does exist and works properly when executed outside the project. The project's `Gemfile` doesn't use `ruby-lsp` at all, nor does it show up in `Gemfile.lock`.

Not sure what else I could be doing, maybe it's a problem with my VSCode install or settings?

---

```
Ruby LSP> Trying to activate Ruby environment with command: /usr/local/bin/bash -ic 'eval "$(rtx env -s bash)" && ruby -rjson -e "printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump(ENV.to_h))"' inside directory: /Users/mvelez/code/pr-report
Ruby LSP> Skipping custom bundle setup since /Users/mvelez/code/pr-report/.ruby-lsp/Gemfile.lock already exists and is up to date
Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2
The Gemfile's dependencies are satisfied
bundler: failed to load command: ruby-lsp (/Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/ruby-lsp)
/Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/rubygems_integration.rb:308:in `block in replace_bin_path': can't find executable ruby-lsp for gem ruby-lsp. ruby-lsp is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/rubygems_integration.rb:336:in `block in replace_bin_path'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/ruby-lsp:25:in `<top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/bundle:25:in `load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/bundle:25:in `<main>'
[Error - 12:47:12 PM] Server process exited with code 1.
[Error - 12:47:12 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Info  - 12:47:12 PM] Connection to server got closed. Server will restart.
true
[Error - 12:47:12 PM] Ruby LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097
Ruby LSP> Skipping custom bundle setup since /Users/mvelez/code/pr-report/.ruby-lsp/Gemfile.lock already exists and is up to date
Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2
The Gemfile's dependencies are satisfied
bundler: failed to load command: ruby-lsp (/Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/ruby-lsp)
/Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/rubygems_integration.rb:308:in `block in replace_bin_path': can't find executable ruby-lsp for gem ruby-lsp. ruby-lsp is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/rubygems_integration.rb:336:in `block in replace_bin_path'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/ruby-lsp:25:in `<top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/bundle:25:in `load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/bundle:25:in `<main>'
[Error - 12:47:14 PM] Server process exited with code 1.
[Error - 12:47:14 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Info  - 12:47:14 PM] Connection to server got closed. Server will restart.
true
[Error - 12:47:14 PM] Ruby LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097
Error restarting the server: Pending response rejected since connection got disposed
Ruby LSP> Skipping custom bundle setup since /Users/mvelez/code/pr-report/.ruby-lsp/Gemfile.lock already exists and is up to date
Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2
The Gemfile's dependencies are satisfied
bundler: failed to load command: ruby-lsp (/Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/ruby-lsp)
/Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/rubygems_integration.rb:308:in `block in replace_bin_path': can't find executable ruby-lsp for gem ruby-lsp. ruby-lsp is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/rubygems_integration.rb:336:in `block in replace_bin_path'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/ruby-lsp:25:in `<top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/bundle:25:in `load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/bundle:25:in `<main>'
[Error - 12:47:17 PM] Server process exited with code 1.
[Error - 12:47:17 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Info  - 12:47:17 PM] Connection to server got closed. Server will restart.
true
[Error - 12:47:17 PM] Ruby LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 12:47:17 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097
Ruby LSP> Skipping custom bundle setup since /Users/mvelez/code/pr-report/.ruby-lsp/Gemfile.lock already exists and is up to date
Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2
The Gemfile's dependencies are satisfied
bundler: failed to load command: ruby-lsp (/Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/ruby-lsp)
/Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/rubygems_integration.rb:308:in `block in replace_bin_path': can't find executable ruby-lsp for gem ruby-lsp. ruby-lsp is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/rubygems_integration.rb:336:in `block in replace_bin_path'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/ruby-lsp:25:in `<top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/bundle:25:in `load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/bundle:25:in `<main>'
[Error - 12:47:18 PM] Server process exited with code 1.
[Error - 12:47:18 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Info  - 12:47:18 PM] Connection to server got closed. Server will restart.
true
[Error - 12:47:18 PM] Ruby LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 12:47:18 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097
Ruby LSP> Skipping custom bundle setup since /Users/mvelez/code/pr-report/.ruby-lsp/Gemfile.lock already exists and is up to date
Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2
The Gemfile's dependencies are satisfied
bundler: failed to load command: ruby-lsp (/Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/ruby-lsp)
/Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/rubygems_integration.rb:308:in `block in replace_bin_path': can't find executable ruby-lsp for gem ruby-lsp. ruby-lsp is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/rubygems_integration.rb:336:in `block in replace_bin_path'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/ruby-lsp:25:in `<top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/bundle:25:in `load'
	from /Users/mvelez/.local/share/rtx/installs/ruby/3.2.2/bin/bundle:25:in `<main>'
[Error - 12:47:20 PM] Server process exited with code 1.
[Error - 12:47:20 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 12:47:20 PM] The Ruby LSP server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 12:47:20 PM] Ruby LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097
[Error - 12:47:20 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097
```

**Comment by truecar-mvelez** [comment]
@vinistock Not that I can see. I checked a few other Gemfiles across my repos, and none seem different. `bundle config list` doesn't show anything, either.

I ended up deleting and re-cloning the problematic repo, and now Ruby LSP works perfectly. Very weird, but I'll close this issue now. Thanks anyway for the help!
