### ISSUE TITLE
server crashes when using private GitHub RubyGems package registries

### ISSUE THREAD

**Issue by GrantBirki** [Shopify/vscode-ruby-lsp#882]
### Operating System

Ubuntu

### Ruby version

3.2.2

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

rbenv

### Description

I only just started using this new VSC extension because the old one I was using is now deprecated. I get the following error when opening any project that has internal Gems (from work) in the project. These "internal" gems are hosted in GitHub's RubyGems package registry instead of on RubyGems.org.

GitHub's RubyGems package registry documentation is available [here](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-rubygems-registry) in case the person who takes a look at this issue is unfamiliar.

When opening projects that have these Gems, the Ruby LSP server instantly fails. I have ruled out there being something wrong with my `ruby-lsp` configuration because if I open a project that does not contain internal Gems from our internal package registry, everything works just fine. The issue is consistent with projects that have internal Gems. I am guessing that something isn't working correctly when `ruby-lsp` tries to `bundle install` and setup its own dependencies. Perhaps it doesn't inherit the permissions that are needed to pull Gems from `rubygems.pkg.github.com/NAMESPACE`.

I use the following command to authenticate with the GitHub RubyGems package registry to pull down internal Gems for my project:

```console
$ bundle config --global https://rubygems.pkg.github.com/NAMESPACE USERNAME:TOKEN
```

ruby-lsp error that I get when opening VSC for a Ruby project:

> Example: `code .`

```text
Ruby LSP> Skipping custom bundle setup since /home/grantbirki/code/<redacted>/.ruby-lsp/Gemfile.lock already exists and is up to date
Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2
Bundler can't satisfy your Gemfile's dependencies.
Install missing gems with `bundle install`.
Fetching gem metadata from https://rubygems.pkg.github.com/<redacted>/..
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Bundler could not find compatible versions for gem
"<redacted>":
  In snapshot (Gemfile.lock):
    <redacted> (= 0.5.2)

  In Gemfile:
    <redacted> (~> 0.5)

Deleting your Gemfile.lock file and running `bundle install` will rebuild your
snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
Bundler could not find compatible versions for gem "<redacted>":
  In Gemfile:
<redacted> (~> 0.5) was resolved to 0.5.2, which
depends on
      <redacted> (= 0.3.4.gffe2410)

Could not find gem '<redacted> (= 0.3.4.gffe2410)', which is required by
gem '<redacted> (~> 0.5)', in rubygems repository
https://rubygems.pkg.github.com/<redacted>/.

The source contains the following gems matching '<redacted>':
  * <redacted>-0.4.0
bundler: failed to load command: ruby-lsp (/home/grantbirki/.rbenv/versions/3.2.2/bin/ruby-lsp)
/home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/resolver.rb:271:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'aws-sdk-ec2 (~> 1)' in locally installed gems. (Bundler::GemNotFound)
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/resolver.rb:254:in `map!'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/resolver.rb:254:in `verify_gemfile_dependencies_are_found!'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/resolver.rb:49:in `start'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/resolver.rb:24:in `resolve'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/definition.rb:480:in `reresolve'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/definition.rb:283:in `resolve'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/definition.rb:488:in `materialize'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/definition.rb:191:in `specs'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/definition.rb:247:in `specs_for'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/runtime.rb:18:in `setup'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler.rb:163:in `setup'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/setup.rb:20:in `block in <top (required)>'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/ui/shell.rb:136:in `with_level'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/ui/shell.rb:88:in `silence'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/setup.rb:20:in `<top (required)>'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/cli/exec.rb:56:in `require_relative'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/cli/exec.rb:56:in `kernel_load'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/cli/exec.rb:23:in `run'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/cli.rb:483:in `exec'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/cli.rb:31:in `dispatch'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/cli.rb:25:in `start'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/exe/bundle:48:in `block in <top (required)>'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
	from /home/grantbirki/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.19/exe/bundle:36:in `<top (required)>'
	from /home/grantbirki/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
	from /home/grantbirki/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'
[Error - 12:00:18 PM] Server process exited with code 1.
[Error - 12:00:18 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 12:00:18 PM] Connection to server got closed. Server will restart.
true
[Error - 12:00:18 PM] Ruby LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

**Comment by GrantBirki** [comment]
Okay I'm actually trying in another project now that doesn't have any funky `X.X.X.<sha>` Gems in it. I'm still getting errors.

In this other repository, I have a `.ruby-lsp/` directory:

```console
$ ls .ruby-lsp/
Gemfile  Gemfile.lock  last_updated  main_lockfile_hash  vendor
```

I can also run the command that you provided earlier:

```console
$ BUNDLE_GEMFILE=.ruby-lsp/Gemfile bundle install
Using rake 13.0.6
Using concurrent-ruby 1.1.10
Using i18n 1.10.0
Using minitest 5.15.0
Using tzinfo 2.0.4
Using activesupport 7.0.3
Using public_suffix 5.0.3
Using addressable 2.8.5
Using ast 2.4.2
Using bundler 2.3.5
Using rexml 3.2.6
Using crack 0.4.5
Using stringio 3.0.9
Using psych 5.1.1.1
Using rdoc 6.6.0
Using io-console 0.6.0
Using reline 0.4.0
Using irb 1.8.3
Using debug 1.8.0
Using diff-lcs 1.5.0
Using docile 1.4.0
Using <redacted> 0.10.2 from source at `.` and installing its executables
Using hashdiff 1.0.1
Using language_server-protocol 3.17.0.3
Using parallel 1.22.1
Using parser 3.1.2.0
Using prism 0.17.1
Using rack 2.2.3.1
Using rainbow 3.1.1
Using regexp_parser 2.5.0
Using rspec-support 3.12.0
Using rspec-core 3.12.2
Using rspec-expectations 3.12.3
Using rspec-mocks 3.12.5
Using rspec 3.12.0
Using rubocop-ast 1.18.0
Using ruby-progressbar 1.11.0
Using unicode-display_width 2.1.0
Using rubocop 1.30.1
Using rubocop-performance 1.14.2
Using rubocop-rails 2.15.0
Using rubocop-github 0.17.0
Using sorbet-runtime 0.5.11120
Using ruby-lsp 0.12.3
Using simplecov-html 0.12.3
Using simplecov_json_formatter 0.1.4
Using simplecov 0.22.0
Using simplecov-erb 1.0.1
Using vcr 6.2.0
Using webmock 3.19.1
Bundle complete! 13 Gemfile dependencies, 50 gems now installed.
Bundled gems are installed into `./.ruby-lsp/vendor/gems`
```

However, when starting the `ruby-lsp` language server (via the VSC button) I get the following error:

```text
2023-11-09 11:32:20.071 [info] Ruby LSP> Skipping custom bundle setup since /home/grantbirki/code/<redacted>/.ruby-lsp/Gemfile.lock already exists and is up to date

2023-11-09 11:32:20.078 [info] Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2

2023-11-09 11:32:20.382 [info] The Gemfile's dependencies are satisfied

2023-11-09 11:32:20.719 [info] bundler: failed to load command: ruby-lsp (/home/grantbirki/.rbenv/versions/3.2.2/bin/ruby-lsp)

2023-11-09 11:32:20.719 [info] /home/grantbirki/code/<redacted>/.ruby-lsp/vendor/gems/ruby/3.2.0/gems/bundler-2.3.5/lib/bundler/rubygems_integration.rb:331:in `block in replace_bin_path': can't find executable ruby-lsp for gem ruby-lsp. ruby-lsp is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
	from /home/grantbirki/code/<redacted>/.ruby-lsp/vendor/gems/ruby/3.2.0/gems/bundler-2.3.5/lib/bundler/rubygems_integration.rb:359:in `block in replace_bin_path'
	from /home/grantbirki/.rbenv/versions/3.2.2/bin/ruby-lsp:25:in `<top (required)>'
	from /home/grantbirki/code/<redacted>/.ruby-lsp/vendor/gems/ruby/3.2.0/gems/bundler-2.3.5/lib/bundler/cli/exec.rb:58:in `load'
	from /home/grantbirki/code/<redacted>/.ruby-lsp/vendor/gems/ruby/3.2.0/gems/bundler-2.3.5/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /home/grantbirki/code/<redacted>/.ruby-lsp/vendor/gems/ruby/3.2.0/gems/bundler-2.3.5/lib/bundler/cli/exec.rb:23:in `run'
	from /home/grantbirki/code/<redacted>/.ruby-lsp/vendor/gems/ruby/3.2.0/gems/bundler-2.3.5/lib/bundler/cli.rb:484:in `exec'
	from /home/grantbirki/code/<redacted>/.ruby-lsp/vendor/gems/ruby/3.2.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /home/grantbirki/code/<redacted>/.ruby-lsp/vendor/gems/ruby/3.2.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/grantbirki/code/<redacted>/.ruby-lsp/vendor/gems/ruby/3.2.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /home/grantbirki/code/<redacted>/.ruby-lsp/vendor/gems/ruby/3.2.0/gems/bundler-2.3.5/lib/bundler/cli.rb:31:in `dispatch'
	from /home/grantbirki/code/<redacted>/.ruby-lsp/vendor/gems/ruby/3.2.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /home/grantbirki/code/<redacted>/.ruby-lsp/vendor/gems/ruby/3.2.0/gems/bundler-2.3.5/lib/bundler/cli.rb:25:in `start'
	from /home/grantbirki/code/<redacted>/.ruby-lsp/vendor/gems/ruby/3.2.0/gems/bundler-2.3.5/exe/bundle:48:in `block in <top (required)>'
	from /home/grantbirki/code/<redacted>/.ruby-lsp/vendor/gems/ruby/3.2.0/gems/bundler-2.3.5/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /home/grantbirki/code/<redacted>/.ruby-lsp/vendor/gems/ruby/3.2.0/gems/bundler-2.3.5/exe/bundle:36:in `<top (required)>'
	from /home/grantbirki/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
	from /home/grantbirki/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'

2023-11-09 11:32:20.722 [info] [Error - 11:32:20 AM] Server process exited with code 1.
2023-11-09 11:32:20.723 [info] [Error - 11:32:20 AM] Server initialization failed.
2023-11-09 11:32:20.723 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-09 11:32:20.723 [info] [Info  - 11:32:20 AM] Connection to server got closed. Server will restart.
2023-11-09 11:32:20.723 [info] true
2023-11-09 11:32:20.723 [info] [Error - 11:32:20 AM] Ruby LSP client: couldn't create connection to server.
2023-11-09 11:32:20.723 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097
```

**Comment by GrantBirki** [comment]
Another odd finding... My `.ruby-version` file at the root of my repository is `3.1.2` but `ruby-lsp` is detecting a completely different version (`3.2.2`):

![image](https://github.com/Shopify/vscode-ruby-lsp/assets/23362539/2cd60516-827e-4dc9-b755-08101fc5c1fd)

**Comment by GrantBirki** [comment]
@vinistock Here is the output from the command listed above:

> Note: I added a bunch of newlines (`\n`) to this output so that it is easier to read as a GitHub comment

```console
$ rbenv exec ruby -rjson -e "STDERR.printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump({ env: ENV.to_h, ruby_version: RUBY_VERSION, 
yjit: defined?(RubyVM::YJIT) }))"

RUBY_ENV_ACTIVATE{"env":{"SHELL":"/bin/bash","SESSION_MANAGER":"local/ubuntu-gh:@/tmp/.ICE-unix/3683,unix/ubuntu-gh:/tmp/.ICE-unix/3683",
"WINDOWID":"58720260","QT_ACCESSIBILITY":"1","COLORTERM":"truecolor","PYENV_SHELL":"bash","XDG_CONFIG_DIRS":"/etc/xdg/xdg-ubuntu:/etc/xdg",
"XDG_MENU_PREFIX":"gnome-","GNOME_DESKTOP_SESSION_ID":"this-is-deprecated","GNOME_SHELL_SESSION_MODE":"ubuntu","SSH_AUTH_SOCK":"/tmp/
ssh-XXXXXX5AJPUr/agent.7093","RBENV_HOOK_PATH":"/home/grantbirki/.rbenv/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks",
"HOMEBREW_PREFIX":"/home/linuxbrew/.linuxbrew","XMODIFIERS":"@im=ibus","DESKTOP_SESSION":"ubuntu","SSH_AGENT_PID":"7094","GPG_TTY":"/dev/pts/
0","GOENV_SHELL":"bash","GTK_MODULES":"gail:atk-bridge","PWD":"/home/grantbirki/code/<redacted>","XDG_SESSION_DESKTOP":"ubuntu",
"LOGNAME":"grantbirki","XDG_SESSION_TYPE":"x11","MANPATH":"/home/linuxbrew/.linuxbrew/share/man:","SYSTEMD_EXEC_PID":"3702","XAUTHORITY":"/
run/user/1000/gdm/Xauthority","GJS_DEBUG_TOPICS":"JS ERROR;JS LOG","WINDOWPATH":"2","NODENV_SHELL":"bash","HOME":"/home/grantbirki",
"USERNAME":"grantbirki","LANG":"en_US.UTF-8","LS_COLORS":"","XDG_CURRENT_DESKTOP":"ubuntu:GNOME",
"INVOCATION_ID":"9adee97c5fd546d9a77200bcb8adec4b","MANAGERPID":"3537","GOROOT":"/home/grantbirki/.goenv/versions/1.21.0",
"ALACRITTY_SOCKET":"/run/user/1000/Alacritty-:1-6859.sock","INFOPATH":"/home/linuxbrew/.linuxbrew/share/info:","GJS_DEBUG_OUTPUT":"stderr",
"LESSCLOSE":"/usr/bin/lesspipe %s %s","XDG_SESSION_CLASS":"user","TERM":"alacritty","LESSOPEN":"| /usr/bin/lesspipe %s","USER":"grantbirki",
"RBENV_DIR":"/home/grantbirki/code/<redacted>","HOMEBREW_CELLAR":"/home/linuxbrew/.linuxbrew/Cellar","DISPLAY":":1","SHLVL":"1",
"GOENV_ROOT":"/home/grantbirki/.goenv","QT_IM_MODULE":"ibus","HOMEBREW_REPOSITORY":"/home/linuxbrew/.linuxbrew/Homebrew","RBENV_VERSION":"3.1.
2","XDG_RUNTIME_DIR":"/run/user/1000","PYENV_ROOT":"/home/grantbirki/.pyenv","JOURNAL_STREAM":"8:50596","XDG_DATA_DIRS":"/usr/share/ubuntu:/
usr/share/gnome:/home/grantbirki/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/
snapd/desktop","PATH":"/home/grantbirki/.rbenv/versions/3.1.2/bin:/home/grantbirki/.rbenv/libexec:/home/grantbirki/.rbenv/plugins/ruby-build/
bin:/home/grantbirki/.pyenv/shims:/home/grantbirki/.pyenv/bin:/home/grantbirki/.nodenv/shims:/home/grantbirki/.goenv/versions/1.21.0/bin:/
home/grantbirki/.goenv/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/grantbirki/.tfenv/bin:/home/grantbirki/.rbenv/
bin:/home/grantbirki/.rbenv/shims:/home/grantbirki/.cargo/bin:/home/grantbirki/bin:/home/grantbirki/.local/bin:/home/grantbirki/bin:/usr/
local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/grantbirki/.goenv/shims:/home/
grantbirki/go/1.21.0/bin","ALACRITTY_LOG":"/tmp/Alacritty-6859.log","GDMSESSION":"ubuntu","DBUS_SESSION_BUS_ADDRESS":"unix:path=/run/user/
1000/bus","RUBYLIB":"/home/grantbirki/.rbenv/rbenv.d/exec/gem-rehash:","RBENV_ROOT":"/home/grantbirki/.rbenv",
"GIO_LAUNCHED_DESKTOP_FILE_PID":"6859","GIO_LAUNCHED_DESKTOP_FILE":"/usr/share/applications/Alacritty.desktop","OLDPWD":"/home/grantbirki/
code","GOPATH":"/home/grantbirki/go/1.21.0"},"ruby_version":"3.1.2","yjit":"constant"}RUBY_ENV_ACTIVATEgrantbirki@ubuntu-gh

```

**Comment by vinistock** [comment]
Okay, then as a next step can you please try running the full command we run for activation?

```shell
/bin/bash -ic 'rbenv exec ruby -rjson -e "STDERR.printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump({ env: ENV.to_h, ruby_version: RUBY_VERSION, yjit: defined?(RubyVM::YJIT) }))"'
```

This should print the correct Ruby version (3.1.2) like the previous command. If not, then we know something with the shell might be messing up the activation.

**Comment by vinistock** [comment]
Okay, so indeed loading your `~/.bashrc` is messing up `rbenv` for some reason. You can confirm if the issue is coming from `~/.bashrc` by running the command without the `i` flag (to avoid loading it) and seeing if it now prints the right Ruby version.

```shell
/bin/bash -c 'rbenv exec ruby -rjson -e "STDERR.printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump({ env: ENV.to_h, ruby_version: RUBY_VERSION, yjit: defined?(RubyVM::YJIT) }))"'
```

If this is really the case, then you'll need to check what exactly in your `~/.bashrc` is causing the issue with `rbenv`.
